#!/bin/bash

#gcc -Wall -O3 -o pandha_pauli_mc.e pandha_pauli_mc.c -lm

#gcc -Wall -O3 -o pandha_pauli_mc.e pandha_only_mc.c -lm

#gcc -Wall -O3 -o check.e check.c -lm

######### For pandha_pauli_spin_mmc.c -lm ###############

gcc -Wall -O3 -o myprogram.e pauli_spin_mmc.c -lm

#/home/gfrank/job_frank/pauli/pauli_512_mmc_dorso/rho_016/myprogram.e -n 512 -rho 0.16 -temp 4.1 -tend 0.1 -delx 0.5 -delp 10.0 -term 1000 -steps 400000 -thsamp 10000 -tsamp 10000 -ctrl 0.1 -tctrl 10 > pauli_mmc_dorso_rho16.dat


./myprogram.e -n 512 -rho 0.16 -temp 4.1 -tend 0.1 -delx 0.5 -delp 10.0 -term 1000 -steps 40 -thsamp 10 -tsamp 10 -ctrl 0.1 -tctrl 10 > pauli_mmc_dorso_rho16.dat

######### For pandha_pauli_spin_mc.c -lm ###############

#gcc -Wall -O3 -o check.e pandha_pauli_spin_mc.c -lm

#./check.e -n 1728 -rho 0.16 -temp 4.1 -tend 4.1 -delx 0.5 -delp 10.0 -term 0 -steps 1500 -thsamp 10 -tsamp 0 -ctrl 0.1 -tctrl 0 

#-initial pandha_pauli_mc_initial_n512.lammpstrj


#> pandha_pauli_mc_rho05_delx02_delp7.dat

#mv pandha_pauli_mc.lammpstrj pandha_pauli_mc_rho05_delx02_delp7.lammpstrj

#notify guillermo.frank@gmail.com pauli_mmc_dorso.e  n512 rho16 pasos 400000 terminado
